### ISSUE TITLE
Unhandled exception System.NullReferenceException

### ISSUE THREAD

**Issue by Sartharon** [mdhiggins/CenterTaskbar#26]
**Describe the bug**
Unhandled exception leads to process termination

**To Reproduce**
Haven't found a way to reproduce it yet since this seems to randomly happen (I'll keep observing what causes this)

**Desktop (please complete the following information):**
 - OS: Windows 10 20h2
 - Version 1.6

**Additional context**
Started with parameter `144` for 144 Hertz display.

<details>
  <summary><b>Event:</b></summary>

 ```
Application: CenterTaskbar.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at CenterTaskbar.TrayApplication.<Start>b__32_0(System.Windows.Automation.AutomationElement)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass42_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Concurrent.Partitioner`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.ForEach[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   at CenterTaskbar.TrayApplication.Start()
   at CenterTaskbar.TrayApplication..ctor(System.Collections.Generic.IReadOnlyList`1<System.String>)
   at CenterTaskbar.Program.Main(System.String[])
 ```
</details>

**Comment by mdhiggins** [comment]
This is an issue with the threading system that I've been unable to get to resolve 100%

If its persistent you can try the fork here
https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.8nt

This uses the older threading system that's less complex and doesn't appear to suffer from this intermittent exception

**Comment by Sartharon** [comment]
Thanks
I'll try to reproduce it a bit longer if i cant reproduce it i'll switch over to 1.8 in the next few days

I'll update this issue incase i got anything to report back

**Comment by Sartharon** [comment]
Not sure if i should have reopened this one to report about Version 1.8nt

With 1.8nt the crash frequency seems to be about the same. I want to point out that due to COVID i'm working from home i open and close hundreds of windows a day and switch between RDP sessions and my local one (not sure if that info helps in anyway).

Anyways here are the 2 different NullReferenceExceptions i got around 6-7hrs into my work day on different days:
<details>
  <summary><b>Event 1:</b></summary>

 ```
Application: CenterTaskbar.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at CenterTaskbar.TrayApplication.SideBoundary(Boolean, Boolean, System.Windows.Automation.AutomationElement, Double, System.Windows.Rect)
   at CenterTaskbar.TrayApplication.PositionLoop(System.Windows.Automation.AutomationElement)
   at CenterTaskbar.TrayApplication.LoopForPosition(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)

 ```
</details>


<details>
  <summary><b>Event 2:</b></summary>

 ```
Application: CenterTaskbar.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at CenterTaskbar.TrayApplication.SideBoundary(Boolean, Boolean, System.Windows.Automation.AutomationElement, Double, System.Windows.Rect)
   at CenterTaskbar.TrayApplication.RelativePos(Double, Boolean, System.Windows.Automation.AutomationElement, Double, System.Windows.Rect)
   at CenterTaskbar.TrayApplication.PositionLoop(System.Windows.Automation.AutomationElement)
   at CenterTaskbar.TrayApplication.LoopForPosition(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart(System.Object)
 ```
</details>

**Comment by mdhiggins** [comment]
Logs were helpful
https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.9

See if that release fixes things

EDIT: This goes back to the original threaded release since the exception was not a threading issue

**Comment by Sartharon** [comment]
You missed to attach the compiled .exe

**Comment by mdhiggins** [comment]
Fixed, my bad

**Comment by Sartharon** [comment]
I'll close this issue since i havent recieved any crashes in the last 2 days compared to daily before 1.9. Thanks

**Comment by mdhiggins** [comment]
Thanks for following up I'll remove the pre release tag today

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.91

**Comment by Sartharon** [comment]
I'm sorry to open this one up again 😥 but since KB4601050 there seem to be a new System.NullReference showing up:

<details>
  <summary><b>Event:</b></summary>

 ```
Application: CenterTaskbar.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at System.Collections.Generic.Dictionary`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].Insert(System.__Canon, System.__Canon, Boolean)
   at CenterTaskbar.TrayApplication.<Start>b__32_0(System.Windows.Automation.AutomationElement)
   at System.Threading.Tasks.Parallel+<>c__DisplayClass42_0`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].<PartitionerForEachWorker>b__1()
   at System.Threading.Tasks.Task.InnerInvokeWithArg(System.Threading.Tasks.Task)
   at System.Threading.Tasks.Task+<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(System.Object)

Exception Info: System.AggregateException
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean)
   at System.Threading.Tasks.Task.Wait(Int32, System.Threading.CancellationToken)
   at System.Threading.Tasks.Parallel.PartitionerForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Concurrent.Partitioner`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.ForEachWorker[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Threading.Tasks.ParallelOptions, System.Action`1<System.__Canon>, System.Action`2<System.__Canon,System.Threading.Tasks.ParallelLoopState>, System.Action`3<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64>, System.Func`4<System.__Canon,System.Threading.Tasks.ParallelLoopState,System.__Canon,System.__Canon>, System.Func`5<System.__Canon,System.Threading.Tasks.ParallelLoopState,Int64,System.__Canon,System.__Canon>, System.Func`1<System.__Canon>, System.Action`1<System.__Canon>)
   at System.Threading.Tasks.Parallel.ForEach[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]](System.Collections.Generic.IEnumerable`1<System.__Canon>, System.Action`1<System.__Canon>)
   at CenterTaskbar.TrayApplication.Start()
   at CenterTaskbar.TrayApplication..ctor(System.Collections.Generic.IReadOnlyList`1<System.String>)
   at CenterTaskbar.Program.Main(System.String[])

 ```
</details>


Not sure if this is the threaded issue you were refering to at the beginning of this thread

**Comment by mdhiggins** [comment]
Hm nah this isn't he thread issue. Not sure why your system is getting so many null returns from the UIAutomation API

Here is another exception wrapper over this method that should have it briefly delay and retry at the point it seems to be throwing this exception

https://github.com/mdhiggins/CenterTaskbar/releases/tag/1.92

**Comment by Sartharon** [comment]
No idea either since i reinstall windows once a year and this one is fresh from december 🙄
I'll reopen in case this happens again

Thank you so much 🧡
